---
- name: Installing Requirements
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Installing Docker
      apt:
        name: docker.io
    
    - name: Installing Docker-compose
      apt:
        name: docker-compose
      
    - name: Installing pip3
      apt:
        name: python3-pip

    - name: Installing python-docker
      pip:
        name: docker